language: c
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - python-pip
      - openssl

install:
  - pip install -r requirements.txt --user
  - sudo apt-add-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update
  - sudo apt-get install -yy gcc-arm-embedded

script:
  - |
    set -e
    mkdir artefacts
    cd src
    for ENFORCE_DEBUG_LOCK in 1 0 ; do
      for CUSTOM_ATTESTATION_CERT in 1 0 ; do
        for TARGET in TOMU MAPLE_MINI BLUE_PILL BLACK_PILL ST_DONGLE ST_DONGLE_NO_PUSH TURTLE_AUTH; do
          make TARGET=${TARGET} CUSTOM_ATTESTATION_CERT=${CUSTOM_ATTESTATION_CERT} ENFORCE_DEBUG_LOCK=${ENFORCE_DEBUG_LOCK} -j4
          if [ "${CUSTOM_ATTESTATION_CERT}" = 0 ] && [ "${ENFORCE_DEBUG_LOCK}" = 1 ] ; then
            cp build/u2f.bin ../artefacts/u2f-${TARGET}.bin
          fi
          openssl ecparam -name prime256v1 -genkey -noout -outform der -out key.der
          ./inject_key.py --key key.der --ctr 1001
          make clean distclean certclean
        done
      done
    done
    cd ..